package com.gorkem.soccercase.model;

public enum Nationality {
    TURKEY, SWITZERLAND, CANADA, JAPAN, GERMANY, AUSTRALIA, UNITED_KINGDOM, UNITED_STATES, SWEDEN, NETHERLANDS, NORWAY, NEW_ZEALAND, FRANCE, DENMARK, FINLAND, CHINA,
    SINGAPORE, ITALY, AUSTRIA, SPAIN, SOUTH_KOREA, LUXEMBOURG, RUSSIA, PORTUGAL, INDIA, BRAZIL
}
