package com.gorkem.soccercase.model;

public enum Position {
    STRIKER, CENTER_FORWARD, WINGERS, LEFT_MID, RIGHT_MID, CENTER_MID, ATTACKING_MID, DEFENSIVE_MID, CENTER_BACK, FULL_BACK, WING_BACKS, SWEEPER, GOALKEEPER
}
